Scheduler/Scheduler/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WorkScheder.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

Scheduler/WorkScheder/urls.py
from django.urls import path
from . import views

app_name = 'worksched'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    #path('init/', views.InitView.as_view(), name='init'),
    path('set-pattern/<int:pk>', views.SetPatternView.as_view(), name='setpattern'),
    path('api/worksched/<int:year>/<int:month>', views.ApiView.as_view(), name='api'),
    path('worksched/<int:year>/<int:month>/image',
        views.getSchedWithImageView.as_view(), name='image'),
]

Scheduler/accounts/urls.py
from django.urls import path, include, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('change-password/<int:pk>',
        auth_views.PasswordChangeView.as_view(
            template_name='accounts/change_password.html',
            success_url=reverse_lazy('accounts:change-password-done')
        ),
        name='change-password'
    ),
    path('change-password/done/',
        auth_views.PasswordChangeDoneView.as_view(
            template_name='accounts/change_password_done.html'
        ),
        name='change-password-done'
    ),
]

Scheduler/templates/base.html
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" href={% static 'images/favicon.ico' %}>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  <link href="{% static 'css/base.css' %}" rel="stylesheet">
  <title>{% if request.path != '/' %}{% block title %}{% endblock %} | {% endif %}Work Calendar</title>
  {% block head %}{% endblock %}
  <script type="text/javascript">
    {% block js %}{% endblock %}
  </script>
</head>
<body>
<div class="container">
  <header>
    <!--<p class="site-name"><a href="{% url 'worksched:index' %}">Work Calendar</a></p>-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <span class="navbar-bland mb-0 h3"><a id="nav-title" href="{% url 'worksched:index' %}">Work Calendar</a></span>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
            {% if user.is_superuser %}
              <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">admin</a></li>
            {% endif %}
            <li class="nav-item"><a class="nav-link" href="{% url 'worksched:setpattern' user.pk %}">Pattern Update</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'accounts:change-password' user.pk %}">Change Password</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li class="nav-item"><a class="nav-link signup" href="{% url 'accounts:signup' %}">Sign up</a></li>
            <li class="nav-item"><a class="nav-link login"  href="{% url 'login' %}">Login</a></li>
          {% endif %}
        </ul>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </nav>
  </header>
  <div class="content">
    {% block contents %}{% endblock %}
  </div>
</div>
</body>
</html>